# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 10
b = 30
a + b

40

# 3.Define a list and replicate in three different ways.

Создал 4 листа разными способами.

In [9]:
list_a = [1, 2, "Python", True, 1.05]
list_b = list("567")
list_c = list(range(5))
list_d = [x for x in range(5) if x % 2 == 0]

print(list_a)
print(list_b)
print(list_c)
print(list_d)

[1, 2, 'Python', True, 1.05]
['5', '6', '7']
[0, 1, 2, 3, 4]
[0, 2, 4]


# 4.Define two lists and merge them together.

Ниже, привожу 3 способа соединить несколько списков в один.

In [13]:
list_m = list_a + list_b
list_m.extend(list_c)
list_m+=list_d

print(list_m)

[1, 2, 'Python', True, 1.05, '5', '6', '7', 0, 1, 2, 3, 4, 0, 2, 4]


# 5. Get the last element of the list and print it.

In [14]:
list_m[-1]

4

# 6.Define a tuple that contains only one element.

In [24]:
tuple_a = 2,
print(f"tuple_a = {tuple_a}, has length = {len(tuple_a)} and it is {type(tuple_a)}")

tuple_a = (2,), has length = 1 and it is <class 'tuple'>


# 7.Define a three-line long string.

Сделал объект string из 3х строк разделённых \n.

In [28]:
list_st = ["Cherevko", "Vladimir", "Igorevich"]
print("\n".join(list_st))

Cherevko
Vladimir
Igorevich


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [29]:
tuple_st = ("Cherevko", "Vladimir", "Igorevich", 1988, 3, 11)
for x in tuple_st:
    print(x)

Cherevko
Vladimir
Igorevich
1988
3
11


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [30]:
def Mul(a,b):
    return a*b

print(Mul(2,3))

6


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [32]:
import numpy as np
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [33]:
import numpy as np
print(np.zeros((4,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [49]:
matrix_mod = np.arange(15).reshape(3,5)
matrix_mod

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [48]:
matrix_a = np.arange(1,5).reshape(2,2)
print(matrix_a, end='\n'*2)
matrix_b = np.arange(5,9).reshape(2,2)
print(matrix_b, end='\n'*2)

matrix_mult = np.dot(matrix_a, matrix_b)
print(matrix_mult)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
